# Generated by Django 5.0.3 on 2024-03-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='meetings',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.meeting'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='preferences',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.preference'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='priority',
            field=models.CharField(choices=[('None', 'None'), ('High Priority', 'High'), ('Medium Priority', 'Med'), ('Low Priority', 'Low')], default='None', max_length=50),
        ),
    ]
