# Generated by Django 5.0.3 on 2024-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_description_alter_calendar_meetings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='meetings',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='preferences',
        ),
        migrations.AddField(
            model_name='calendar',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='calendars.meeting'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='calendars.preference'),
        ),
    ]
