# Generated by Django 5.0.1 on 2024-03-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0007_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='preference',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
