# Generated by Django 5.0.3 on 2024-03-29 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitee'),
        ('calendars', '0009_rename_participants_meeting_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='meetings',
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(related_name='invitees', to='accounts.invitee'),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
