# Generated by Django 5.0.3 on 2024-03-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_invitee_alter_calendar_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.CharField(choices=[('Not Accepted', 'No'), ('Accepted', 'Yes')], default='Not Accepted', max_length=50),
        ),
    ]
