# Generated by Django 5.0.3 on 2024-03-10 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.CharField(choices=[('None', 'None'), ('High Priority', 'High'), ('Medium Priority', 'Med'), ('Low Priority', 'Low')], default='None', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.CharField(choices=[('None', 'None'), ('High Priority', 'High'), ('Medium Priority', 'Med'), ('Low Priority', 'Low')], default='None', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('meetings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.meeting')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.preference')),
            ],
        ),
    ]
