# Generated by Django 5.0.3 on 2024-03-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_remove_meeting_user_meeting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
    ]
