# Generated by Django 5.0.3 on 2024-03-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0008_alter_preference_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='participants',
            new_name='user',
        ),
    ]
