# Generated by Django 5.0.3 on 2024-03-30 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_alter_invitee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='invitee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='invitedUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
