# Generated by Django 5.0.3 on 2024-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0014_alter_invitee_invitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='invitees', to='calendars.invitee'),
        ),
    ]
