# Generated by Django 5.0.3 on 2024-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0015_calendar_end_date_calendar_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='calendar_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='calendar_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
